HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "01/2024 - 05/2027"
      institution: "San Jose State University"
      logo: "./config/assets/icons/nehs.png"
      description: |
        M.S. in Artificial Intelligence — Expected May 2027
        GPA: 3.95/4.0
        Online graduate program designed for full-time working professionals, led by Professor Wencen Wu.
      coursework:
        - "Python"
        - "C++"
        - "Machine Learning"
        - "Data Engineering"
        - "Data Mining"
        - "Deep Learning"
        - "Reinforcement Learning"
        - "Natural Language Processing"
        - "Intelligent Autonomous System"
        - "Cloud Technologies"
    - period: "08/2018 - 05/2022"
      institution: "San Jose State University"
      logo: "./config/assets/icons/chalmers.jpeg"
      description: |
        B.S in Software Engineering 
        GPA: 3.58/4.0
        Graduated Cum Laude
        Dean's Scholar
        First-Generation College Graduate
      coursework:
        - "Java"
        - "Data Structures & Algorithms"
        - "Operating Systems"
        - "Object Oriented Programming"
        - "Assembly"
        - "Computer Architecture"
        - "Computer Networks"
        - "Database Management"
        - "Information Security"
        - "Software Design"

EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "2010 — 2013"
      position: "Web Designer"
      description: "Worked on the design and development of websites for small to medium-sized businesses. Collaborated closely with developers to ensure responsive and user-friendly designs. Led the redesign of the company’s website, improving user engagement by 25%."
    - period: "2013 — 2015"
      position: "Art Director"
      description: "Led a team of designers to create visually stunning campaigns for major clients in the advertising industry. Managed the creative direction of print and digital media, ensuring consistent branding and high-quality designs. Oversaw the production of advertisements that won industry awards."
    - period: "2015 — Present"
      position: "Creative Director"
      description: "Direct and oversee the creative process for a range of projects, from concept to execution. Lead cross-functional teams to create innovative design solutions for branding, marketing, and digital experiences. Recently led the redesign of a global brand’s digital presence, increasing online sales by 40%."

LANGUAGES:
  enabled: true
  display_progress_bars: true
  display_percentage_values: true
  label: "Languages"
  items:
    - language: "English"
      proficiency: "100%"
    - language: "Chinese - Cantonese"
      proficiency: "80%"
    - language: "Chinese - Mandarin"
      proficiency: "60%"

SKILLS:
  enabled: true
  display_progress_bars: true
  display_percentage_values: true
  label: "My Skills"
  items:
    - skill: "Web Design"
      proficiency: "80%"
    - skill: "Graphic Design"
      proficiency: "70%"
    - skill: "Branding"
      proficiency: "90%"
    - skill: "WordPress"
      proficiency: "50%"
